version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.6.12
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/project

commands:
  save_deps_cache:
    steps:
      - save_cache:
          paths:
            - ~/.cache/pip
            - ~/.venv
          key: v1-dependencies-{{ checksum "requirements/requirements-all.txt" }}
  restore_deps_cache:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements/requirements-all.txt" }}
  save_project_workspace:
    steps:
      - persist_to_workspace:
          root: ~/
          paths:
            - project/
            - .venv/
  restore_project_workspace:
    steps:
      - attach_workspace:
          at: ~/
      - run: source ~/.venv/bin/activate

jobs:
  setup_project:
    executor: docker-executor
    environment:
      CRYPTOGRAPHY_DONT_BUILD_RUST: 1
    steps:
      - checkout
      - restore_deps_cache
      - run: python -m venv --copies ~/.venv
      - run: source ~/.venv/bin/activate
      - run: make install_dev
      - save_deps_cache
      - save_project_workspace
  flake8:
    executor: docker-executor
    steps:
      - restore_project_workspace
      - run: make flake8
  mypy:
    executor: docker-executor
    steps:
      - restore_project_workspace
      - run: make mypy
  pylint:
    executor: docker-executor
    steps:
      - restore_project_workspace
      - run: make pylint
  docscheck:
    executor: docker-executor
    steps:
      - restore_project_workspace
      - run: make docscheck
  packagecheck:
    executor: docker-executor
    steps:
      - restore_project_workspace
      - run: make packagecheck
  test:
    executor: docker-executor
    steps:
      - restore_project_workspace
      - run: make test ARGS="-v --cov --cov-report xml"

workflows:
  workflow:
    jobs:
      - setup_project
      - flake8:
          requires:
            - setup_project
      - mypy:
          requires:
            - setup_project
      - pylint:
          requires:
            - setup_project
      - docscheck:
          requires:
            - setup_project
      - packagecheck:
          requires:
            - setup_project
      - test:
          requires:
            - flake8
            - mypy
            - setup_project
